### PR TITLE
added a few

### PR DESCRIPTION
**Pull request by Gopro336**
just some off the top of my head, there are way more lol

### CODE REVIEW

**Comment by master7720** [comment]
you should add Gopro336 heard he skidded konas

**Comment by Sxmurai** [comment]
@Gopro336 add the part where Sjnez skidded SalHack blink and added a whole new Packet event from SalHack (phobos already had a packet event) and he also pasted in the Alpine code, without even adding Alpine to his build.gradle

Proof: https://github.com/Sjnez613/RenoSense-Rewrite/commit/082161d19b2ec272fd64951cd1b63fe2a299ae58

**Comment by Gopro336** [comment]
💀

**Comment by Gopro336** [comment]
added it lol

**Comment by Sxmurai** [comment]
> Hollow - incel that seems to somewhat know java yet **thier** client "Trollgod" is worthless, phobos pasted garbage.

**Comment by Sxmurai** [comment]
> Sjnez - OyVey/Phobos fetish, Skidded just about any client in order to make "Renosense". Pasted salhack PacketEvent and event bus for one module even though his phobos base already had **thoes** 💀.

**Pull request merged**
