### PR TITLE
im not korean

### PR DESCRIPTION
**Pull request by Wolfsurge**
im welsh/british (and i credit people)

### CODE REVIEW

**Comment by Sxmurai** [comment]
@Wolfsurge this you? https://github.com/Sxmurai/xeno-client-buildable

**Comment by HausemasterIssue** [comment]
Are you mad about this? It's funny I don't get why you would cope over it lol.

**Comment by Sxmurai** [comment]
+ https://github.com/Sxmurai/xeno-client-buildable/tree/main/src/main/java/me/wolfsurge/api/gui/font skided from liquidbounce, i dont see you crediting liquidbounce for the font renderer, yet you say in this commit that you credit people? hm.

**Comment by Sxmurai** [comment]
oh and btw, liquidbounce is GPL-3.0, you cant copy their code lul

```
If you do decide to use ANY code from the source:

    You must disclose the source code of your modified work and the source code you took from this project. This means you are not allowed to use code from this project (even partially) in a closed-source (or even obfuscated) application.
    Your modified application must also be licensed under the GPL
```

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/README.md

**Comment by notperry12345678902** [comment]
british/korean same thing

**Pull request closed without merging**
